version: '3.9'

services:
    nginx:
        build: requirements/nginx/
        ports: 
        - "443:443"
        - "80:80"
        depends_on:
            - wordpress
        command: tail -f /dev/null
        env_file:
            - .env
        ## Esto sobra buscar una manera mejor
        volumes:
        - wp-website:/var/www/html
        networks:
        - default
    wordpress:
        build: requirements/wordpress/
        volumes:
        - wp-website:/usr/share/webapps
        - wp-database:/var/lib/mysql
        depends_on:
            - mariadb
        command: tail -f /dev/null
        env_file:
            - .env
        networks:
        - default
      ## Esto tambien sobra buscar algo mejor
    mariadb:
        build: requirements/mariadb
        env_file:
            - .env
        command: tail -f /dev/null
        volumes:
        - wp-database:/var/lib/mysql
        networks:
        - default

volumes:
    wp-database:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./wp-database/
    wp-website:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./wp-website/
networks:
    default:
