version: '3.9'

services:
    nginx:
        build: requirements/nginx
        ports:
        - "443:443"
        - "80:80"
        command: tail -f /dev/null
        env_file:
            - .env
        volumes:
            - wp-website:/var/www/wordpress
        networks:
            - default
    wordpress:
        build: requirements/wordpress
        volumes:
            - wp-website:/var/www/wordpress
        command: tail -f /dev/null
        env_file:
            - .env
        networks:
            - default
    mariadb:
        build: requirements/mariadb
        env_file:
            - .env
        command: tail -f /dev/null
        volumes:
            - wp-database:/var/lib/mysql
        networks:
            - default
volumes:
    wp-database:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./wp-database/
    wp-website:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./wp-website/

networks:
    default:
