version: '3.9'

services:
  nginx:
    build: requirements/nginx
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - wp-website:/var/www/wordpress
    networks:
      - default
    restart:
      on-failure
    depends_on:
     - wordpress

  wordpress:
    build: requirements/wordpress
    volumes:
      - wp-website:/var/www/wordpress
    command: /init.sh
    env_file: .env
    networks:
      - default
    restart:
      on-failure
    depends_on:
      - mariadb

  mariadb:
    build: requirements/mariadb
    env_file: .env
    command: /setup.sh
    volumes:
      - wp-database:/var/lib/mysql
    networks:
      - default
    restart:
      on-failure
    expose:
      - "3306"
  
volumes:
    wp-database:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/mviudes/data/wp-database
    wp-website:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/mviudes/data/wp-website/

networks:
    default:
